-- Products (from catalogue) — using local images from /images/
INSERT INTO products (slug, name, icon, category, image_url, description, specs, badges, featured, sort_order) VALUES
('junior-wash-care-label', 'Junior Wash Care Label', '🏷️', 'labels',
 '/images/kids apparel wash.jpeg',
 '5-inch & 4.5-inch lengths, 1.2cm stitching. Multi-language print. Junior, Disney, Bluey branded options.',
 ARRAY['OEKO-TEX','5 inch / 4.5 inch','Soft Finish'], ARRAY['OEKO-TEX®'], TRUE, 1),
('character-main-label', 'Character Main Label', '🔖', 'labels',
 '/images/Character Main Label.jpeg',
 'Custom length, cut & center-creased. Marvel, Disney, Bluey, Nickelodeon brand licensed printing.',
 ARRAY['OEKO-TEX','Character Brands','Custom Length'], ARRAY['OEKO-TEX®'], TRUE, 2),
('india-babyshop-wash-care-label', 'India Babyshop Wash Care Label', '👶', 'labels',
 '/images/Baby Wash Care Label.jpeg',
 '2.5-inch length with 1.2cm stitching. Specifically designed for IND Baby Shop range. OEKO-TEX certified inks.',
 ARRAY['OEKO-TEX','2.5 inch','Baby Safe'], ARRAY['OEKO-TEX®'], FALSE, 3),
('junior-collection-hang-tags', 'Junior Collection Hang Tags', '🎫', 'hang-tags',
 '/images/Junior Collection Hang Tags.jpeg',
 'BOYS/GIRLS collection tags. 700 GSM thick premium board. FSC number printed on back. Single-side printing.',
 ARRAY['FSC Certified','700 GSM','Single Side'], ARRAY['FSC®'], TRUE, 4),
('disney-hang-tag', 'Disney Hang Tag', '🎠', 'hang-tags',
 '/images/Die-Cut Character Hang Tags.jpeg',
 '350 GSM premium board, double-sided lamination finish. Full-colour Disney character prints with vibrant inks.',
 ARRAY['FSC Certified','350 GSM','Double Laminated'], ARRAY['FSC®'], TRUE, 5),
('character-hang-tags', 'Character Hang Tags', '🦸', 'hang-tags',
 '/images/Character Hang Tags.jpeg',
 'Various styles & sizes. Front & back high-quality printing. 350 GSM double-laminated. Includes size sticker & wash care label.',
 ARRAY['350 GSM','Double Side','Multi-Character'], ARRAY['FSC®'], FALSE, 6),
('under-garment-junior-photo-card', 'Under Garment Junior Photo Card', '📸', 'cards',
 '/images/Under Garment Photo Card.jpeg',
 'Single-side printed. Sizes vary by piece count. 350 GSM board thickness. Used for size grids and product info.',
 ARRAY['350 GSM','Single Side','Custom Size'], ARRAY[]::TEXT[], FALSE, 7),
('agency-photo-card', 'Agency Photo Card', '🎨', 'cards',
 '/images/Agency Photo Card.jpeg',
 'Available for IND BABYSHOP. 300 GSM board thickness. Character photo cards for Marvel, Disney, Stitch, Paw Patrol.',
 ARRAY['300 GSM','Character','Agency'], ARRAY[]::TEXT[], FALSE, 8),
('disney-junior-hanger-cards', 'Disney & Junior Hanger Cards', '🪝', 'cards',
 '/images/Hanger Cards.jpeg',
 'DISNEY: 3-ply carton thickness, no separate hanger needed. JUNIOR: 700 GSM, various pack sizes and dimensions.',
 ARRAY['700 GSM','Cost Saving','Multi-Pack'], ARRAY[]::TEXT[], FALSE, 9),
('inner-cards', 'Inner Cards (DISNEY & Junior 7PK)', '📄', 'cards',
 '/images/Inner Packaging Cards.jpeg',
 'DISNEY insert card inside packaging — 400 GSM. JUNIOR 7PK inner card — 700 GSM, helps in packaging process.',
 ARRAY['400–700 GSM','Packaging Insert'], ARRAY[]::TEXT[], FALSE, 10),
('character-brand-stickers', 'Character & Brand Stickers', '🩹', 'stickers',
 '/images/Character & Brand Stickers.jpeg',
 'Size stickers, brand logos, pack-info stickers. Multi-language. Age & weight range formats for baby/kids wear.',
 ARRAY['OEKO-TEX','Multi-Language','Size Range'], ARRAY['OEKO-TEX®'], TRUE, 11),
('packing-boxes-stationery', 'Packing Boxes & Stationery', '📦', 'packaging',
 '/images/Packing Boxes & Stationery.jpeg',
 'Custom printed packaging boxes, printed stationery items. Offset printing, lamination, die cutting, hole punching.',
 ARRAY['FSC Certified','Custom Print','Offset'], ARRAY['FSC®'], FALSE, 12)
ON CONFLICT (slug) DO NOTHING;

-- Blog posts
INSERT INTO blog_posts (slug, title, category, icon, excerpt, read_minutes, published_at) VALUES
('fsc-certification-matters', 'Why FSC Certification Matters for Your Brand', 'Sustainability', '🌱',
 'Understanding how FSC-certified paper and board helps your brand meet global sustainability standards and retailer requirements.', 5, '2026-06-10'),
('oeko-tex-standard-100-guide', 'OEKO-TEX Standard 100: What Garment Brands Need to Know', 'Industry Guide', '🏷️',
 'A complete guide to the OEKO-TEX Standard 100 certification and why it''s essential for baby and children''s wear labels.', 4, '2026-05-12'),
('hang-tags-that-sell', 'Modern Garment Branding: Hang Tags That Sell', 'Design Tips', '🎨',
 'How the right hang tag design, board weight, and lamination finish elevates your product at the point of sale.', 6, '2026-04-08'),
('rotary-vs-offset-printing', 'Rotary Printing vs. Offset Printing: Which Is Right for You?', 'Technology', '⚙️',
 'Breaking down when to use rotary printing for high-volume labels versus offset printing for tags and cards.', 5, '2026-03-15'),
('sustainable-packaging-2026', 'Sustainable Packaging Design for 2026 and Beyond', 'Packaging', '📦',
 'How leading garment brands are redesigning their packaging to reduce waste while maintaining premium shelf presence.', 4, '2026-02-11'),
('artwork-submission-guide', 'Artwork Submission Guide: File Formats, Bleeds & Colour Profiles', 'Specifications', '📐',
 'Everything your design team needs to know when preparing files for label, hang tag, and sticker production.', 7, '2026-01-20')
ON CONFLICT (slug) DO NOTHING;